[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
src_dir = Firmware
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/DHT sensor library
monitor_speed = 9600
